title: looping-alt
hero_image: images/banner.png
description: looping-alt description
version: 4
listed: false
copyedit: false
last_tested: "2020-08-05"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
