title: Looping sprites alternative
hero_image: images/banner.png
description: looping-alt description
version: 4
listed: false
copyedit: false
last_tested: "2020-08-05"
steps:
  - title: Introduction
  - title: Choose your theme
  - title: Get a sprite moving
